# Generated by Django 4.1 on 2024-04-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingHome', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
