# Generated by Django 5.0.6 on 2024-05-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingPolls', '0007_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
