# Generated by Django 4.1 on 2024-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VotingResult', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
